// AUTH USER
export const AUTH_USER_INIT = 'AUTH_USER_INIT';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_FAIL = 'AUTH_USER_FAIL';

// CHECK USER
export const CHECK_USER_INIT = 'CHECK_USER_INIT';
export const CHECK_USER_SUCCESS = 'CHECK_USER_SUCCESS';
export const CHECK_USER_FAIL = 'CHECK_USER_FAIL';

// SIGN OUT
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';

// CREATE PROJECT
export const CREATE_PROJECT_INIT = 'CREATE_PROJECT_INIT';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAIL = 'CREATE_PROJECT_FAIL';

// GET PROJECTS
export const GET_PROJECTS_INIT = 'GET_PROJECTS_INIT';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_FAIL = 'GET_PROJECT_FAIL';

// SET ACTIVE PROJECT
export const SET_PROJECT_SUCCESS = 'SET_PROJECT_SUCCESS';

// REMOVE PROJECT
export const REMOVE_PROJECT_INIT = 'REMOVE_PROJECT_INIT';
export const REMOVE_PROJECT_SUCCESS = 'REMOVE_PROJECT_SUCCESS';
export const REMOVE_PROJECT_FAIL = 'GET_PROJECT_FAIL';
