// AUTH USER
export const AUTH_USER_INIT = 'AUTH_USER_INIT';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_FAIL = 'AUTH_USER_FAIL';

// CHECK USER
export const CHECK_USER_INIT = 'CHECK_USER_INIT';
export const CHECK_USER_SUCCESS = 'CHECK_USER_SUCCESS';
export const CHECK_USER_FAIL = 'CHECK_USER_FAIL';

// CREATE PROJECT
export const CREATE_PROJECT_INIT = 'CREATE_PROJECT_INIT';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAIL = 'CREATE_PROJECT_FAIL';
